version: "3.9"
services:
  zookeeper:
    image: bitnami/zookeeper:3.9
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3.7
    depends_on: [zookeeper]
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes

  kafka-exporter:
    image: danielqsj/kafka-exporter:v1.7.0
    depends_on: [kafka]
    command: ["--kafka.server=kafka:9092"]
    ports:
      - "9308:9308"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on: [kafka]
    ports:
      - "8085:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092

  flink-jobmanager:
    image: flink:1.19.1-scala_2.12
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
    command: jobmanager
    ports:
      - "8081:8081"   # Flink UI
      - "9249:9249"   # Prometheus metrics
    volumes:
      - ./flink/conf/flink-conf.yaml:/opt/flink/conf/flink-conf.yaml:ro
      - ./sql:/sql:ro
    depends_on: [kafka]

  flink-taskmanager:
    image: flink:1.19.1-scala_2.12
    depends_on: [flink-jobmanager]
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
    ports:
      - "9250:9250"   # Prometheus metrics (dynamic range in conf)
    volumes:
      - ./flink/conf/flink-conf.yaml:/opt/flink/conf/flink-conf.yaml:ro

  sql-client:
    image: flink:1.19.1-scala_2.12
    depends_on: [flink-jobmanager]
    entrypoint: ["/bin/bash","-lc","sleep infinity"]
    volumes:
      - ./sql:/sql:ro

  prometheus:
    image: prom/prometheus:v2.55.0
    depends_on: [flink-jobmanager, kafka-exporter]
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/alerts.yml:/etc/prometheus/alerts.yml:ro

  alertmanager:
    image: prom/alertmanager:v0.27.0
    depends_on: [prometheus]
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro

# networks: default docker network is fine
